Correct bad syntax; improve traps.

diff --git a/libexec/actions/start b/libexec/actions/start
--- a/libexec/actions/start
+++ b/libexec/actions/start
@@ -67,22 +67,22 @@ else
   # Determine allocated GPU
   if [ "$CUDA_VISIBLE_DEVICES" ]; then
     _BUSID_HEX=$(
-      _nvidia_smi --query-gpu=pci.bus \
-                  --format=csv,noheader \
-                  --id=${CUDA_VISIBLE_DEVICES%%,*}
-              )
+	nvidia-smi --query-gpu=pci.bus \
+            --format=csv,noheader \
+            --id=${CUDA_VISIBLE_DEVICES%%,*}
+    )
   else
     # If no GPU allocated, choose next free GPU
     _BUSID_HEX=$(
-      nvidia-smi --query-gpu=memory.used,pci.bus \
-                 --format=csv,noheader,nounits | \
-        grep '^0, ' | head -n1 | cut -f2 -d' '
-              )
+	nvidia-smi --query-gpu=memory.used,pci.bus \
+            --format=csv,noheader,nounits | \
+            grep '^0, ' | head -n1 | cut -f2 -d' '
+    )
   fi
 fi
 
 if [ -z "$_BUSID_HEX" ]; then
-  echo -e "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bnot found     \n" 1>&2
+  echo -e "\b\b\b\b\b\b\b\b\b\b\b\b\bnot found     \n" 1>&2
   echo "${FLIGHT_PROGRAM_NAME:-gl}: unable to determine target GPU" 1>&2
   exit 1
 fi
@@ -185,7 +185,11 @@ _flightgl_cleanup() {
     [ -d /proc/${_XORG_PID} ] && kill ${_XORG_PID}
 }
 
-trap "exit \\\$exit_code" INT TERM
+if [ ! -t 1 ]; then
+  trap "exit \\\$exit_code" INT TERM
+else
+  trap "exit \\\$exit_code" TERM
+fi
 trap "exit_code=\\\$?; _flightgl_cleanup; kill 0" EXIT
 
 export VGL_DISPLAY=${_DISPLAY}.0
